### PR TITLE
Fix smashing objects in overlapping rooms

### LINKED ISSUE #4949: TRII: Ice Palace. Bell from room 48 can be shot from room 55
Version: TRX 1.2.2-201-g5f4e23d

Try:
play 14
tp 55

Use fly cheat to activate the platform above. Now you an stand on it and shoot at the bell in this room. It opens the second gate. The first gate should be opened by bell in room 48 with the jump pad.

BUT: If you stand there and shooting around you you can also hit the bell of room 48. It seems like the bullets go through walls. Both gates are open now.

Image

Image

Image

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/develop/docs/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #4949.

Reason for the bug: non-Euclidean Tomb geometry
image

Modified Aredfan's scenario to include a valid path too:
[test-bell-smash.txt](https://github.com/user-attachments/files/25497523/test-bell-smash.txt)

### CODE REVIEW

File: src/trx/game/collision/los.c [hunk 1]
```diff
@@ -139,12 +166,17 @@ int32_t LOS_CheckSmashable(
         }
 
         XYZ_32 hit_pos;
-        if (!M_ItemIntersectSegment(start, target, item, &hit_pos)) {
+        if (!M_ItemIntersectSegment(start.pos, target.pos, item, &hit_pos)) {
+            continue;
+        }
+
+        if (target.room_num != NO_ROOM && item->object_id == O_BELL
```
Comment (lahm86) [inline src/trx/game/collision/los.c]: Is the `O_BELL` constraint needed given the condition above on L162? Just thinking if the situation were to apply to windows.

Comment (rr-) [reply src/trx/game/collision/los.c]: No, it's a dumb leftover from my LLM session. Thank you

Comment (rr-) [reply src/trx/game/collision/los.c]: Fixed :relieved:

**Review by aredfan — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]
