### PR TITLE
tr1/camera: fix potential division by zero

### LINKED ISSUE #1671: OG bug: camera clipping can cause a crash
This is very specific to certain level design and isn't an issue in the original levels AFAIK. In the attached, if you pull the block and hold look, the game crashes to desktop.

[LEVEL1.zip](https://github.com/user-attachments/files/17266252/LEVEL1.zip)

The pushblock triggers a flipmap, which has a wall where the block sits, but the pushblock is also deactivated at the same time.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #1671.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This avoids the crash in the custom level in the issue itself. The camera still shows the void briefly before returning to Lara but the check in place is clearly safer for this kind of situation.

### CODE REVIEW

File: src/tr1/game/camera.c [hunk 1]
```diff
@@ -782,14 +782,21 @@ static void M_Clip(
     const int32_t target_y, const int32_t left, const int32_t top,
     const int32_t right, const int32_t bottom)
 {
+    const int32_t x_diff = *x - target_x;
+    const int32_t y_diff = *y - target_y;
+
     if ((right > left) != (target_x < left)) {
-        *y = target_y + (*y - target_y) * (left - target_x) / (*x - target_x);
+        if (x_diff) {
+            *y = target_y + (*y - target_y) * (left - target_x) / x_diff;
```
Comment (rr-) [inline src/tr1/game/camera.c]: Can it be simplified to `*y = target_y + (left - target_x) * y_diff / x_diff`?

Comment (lahm86) [reply src/tr1/game/camera.c]: Yes 😄

**Review by walkawayy — APPROVED** [review]

**Review by aredfan — APPROVED** [review]

**Review by rr- — APPROVED** [review]
