### PR TITLE
inv-ring: fix medi packs flashing

### LINKED ISSUE #4211: TRX bug: health bar issue while in the inventory
Regression since [4.14](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.14) and [1.4](https://github.com/LostArtefacts/TRX/releases/tag/tr2-1.4)

________________

1. launch the game
2. `/play 1`
3. use the all items cheat
4. <kbd>F2</kbd> and/or `/debug pos 1` (this helps to make the issue more visible)

With the focus on the compass/stopwatch, hold down the right arrow and observe the healthbar briefly appear and disappear as we cycle pass the medipack objects.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #4211.

### CODE REVIEW

File: src/libtrx/game/inventory_ring/control.c [hunk 1]
```diff
@@ -126,7 +126,7 @@ static void M_RingNotActive(
 
     case O_SMALL_MEDIPACK_OPTION:
     case O_LARGE_MEDIPACK_OPTION:
-        Overlay_SetHealthBarTimer(40);
+        Overlay_ForceHealthBar(true);
```
Comment (rr-) [inline src/libtrx/game/inventory_ring/control.c:129]: Note that consuming a medi pack will still cause the health bar to show up as expected, as this is handled elsewhere.

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍

**Review by lahm86 — APPROVED** [review]
