### PR TITLE
tr1/objects/bear: apply AI fix in bear control

### LINKED ISSUE #2559: TR1X bug: fix bear ai is affecting demos
**Regression since:** [4.8](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.8)

_____________

Prior to 4.8, the `Fix bear AI` option would be forced off for the demo modes. This seems to no longer be the case because demo 1 is being affected by the option if enabled.

#1370 for reference.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #2559.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This moves the bear AI fix to the control routine as otherwise when the demo alters the setting, its effect has already taken place in the bear setup function. It's not ideal calling it on every frame a bear is active, but I suppose a benefit is that it does allow changing the setting in-game with the console without having to reload.

### CODE REVIEW

File: src/tr1/game/objects/creatures/bear.c [hunk 1]
```diff
@@ -76,6 +71,7 @@ static void M_Setup(OBJECT *const obj)
 
 static void M_Control(const int16_t item_num)
 {
+    Object_Get(O_BEAR)->pivot_length = g_Config.gameplay.fix_bear_ai ? 0 : 500;
```
Comment (rr-) [inline src/tr1/game/objects/creatures/bear.c]: Let's avoid assignments to a pointer from a function call, eg let's introduce an `obj` variable on which we later execute state-altering operations.

File: src/tr1/game/objects/creatures/bear.c [hunk 2]
```diff
@@ -76,6 +71,8 @@ static void M_Setup(OBJECT *const obj)
 
 static void M_Control(const int16_t item_num)
 {
+    OBJECT *const obj = Object_Get(O_BEAR);
```
Comment (rr-) [inline src/tr1/game/objects/creatures/bear.c]: One last nitpick - can we use `item->object_id`?

**Review by rr- — APPROVED** [review]

File: src/tr1/game/objects/creatures/bear.c (hunk 2 above)
Comment (lahm86) [reply src/tr1/game/objects/creatures/bear.c]: Of course, my bad. I was a bit hasty with this 😄

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍
