### PR TITLE
Fix bridges embedding under the floor

### LINKED ISSUE #523: Restore Lost Valley broken bridge tiles
TombATI/TR1M
20220421_214939_Lost_Valley

PS1
SLES-00024_2022-04-21_22-36-52
SLES-00024_2022-04-21_22-37-00

### PR DESCRIPTION
**Pull request by walkawayy**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed bridges at floor level appearing under the floor.
...

### CODE REVIEW

File: src/game/objects/general/bridge.c [hunk 1]
```diff
@@ -73,20 +76,51 @@ static int32_t Bridge_GetOffset(
...
+            bridge_height =
+                ABS(bounds[FRAME_BOUND_MAX_Y]) - ABS(bounds[FRAME_BOUND_MIN_Y]);
+            item->pos.y = floor_height - bridge_height;
+        }
+    }
+}
+
 void Bridge_SetupFlat(OBJECT_INFO *obj)
 {
+    obj->initialise = Bridge_FixEmbedded;
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Let's be consistent with `bat.c`:

1. `obj->initialise = Bridge_Initialise`
2. ```c
    void Bridge_Initialise(int16_t item_num)
    {
        // Some comment about embedded bridges
        Bridge_FixEmbeddedPosition(item_num);
    }
    ```

Note how initialise is not static. It goes in .h too.

File: src/game/objects/general/bridge.c [hunk 2]
```diff
@@ -73,20 +76,51 @@ static int32_t Bridge_GetOffset(
     return offset;
 }
 
+static void Bridge_FixEmbedded(int16_t item_num)
+{
+    ITEM_INFO *item;
+    FLOOR_INFO *floor;
+    int32_t x, y, z;
+    int16_t room_number, floor_height, old_anim, old_frame, bridge_height;
+    int16_t *bounds;
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Please move all variables to their usage

File: src/game/objects/general/bridge.c [hunk 3]
```diff
@@ -73,20 +76,51 @@ static int32_t Bridge_GetOffset(
...
+
+    item = &g_Items[item_num];
+    if (item->status != IS_ACTIVE) {
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Consider early exit:

```c
if (item->status == IS_ACTIVE) {
    return;
}
```

File: src/game/objects/general/bridge.c [hunk 4]
```diff
@@ -73,20 +76,51 @@ static int32_t Bridge_GetOffset(
...
+        x = item->pos.x;
+        y = item->pos.y;
+        z = item->pos.z;
+        room_number = item->room_number;
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Let's name this `room_num` (this is a change I'm introducing in T3M)

File: src/game/objects/general/bridge.c [hunk 5]
```diff
@@ -73,20 +76,51 @@ static int32_t Bridge_GetOffset(
...
+
+        floor = Room_GetFloor(x, y, z, &room_number);
+        floor_height = Room_GetHeight(floor, x, y, z);
+
+        // Only move the bridge up if it's at floor level.
+        if (item->floor == floor_height) {
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Again consider an early exit to reduce indentation below

**Review by rr- — CHANGES_REQUESTED** [review]
Cosmetic remarks but LGTM otherwise

File: src/game/objects/general/bridge.c (hunk 2 above)
Comment (walkawayy) [reply src/game/objects/general/bridge.c]: Yes I don't like this style either. I based it on bat.c which does this.

File: src/game/objects/general/bridge.c (hunk 3 above)
Comment (walkawayy) [reply src/game/objects/general/bridge.c]: I removed this check since bridges never have any `ITEM_STATUS`. It was a copy and paste relic from the bat fix.

File: src/game/objects/general/bridge.h [hunk 6]
```diff
@@ -8,6 +8,7 @@ void Bridge_SetupFlat(OBJECT_INFO *obj);
 void Bridge_SetupTilt1(OBJECT_INFO *obj);
 void Bridge_SetupTilt2(OBJECT_INFO *obj);
 void Bridge_SetupDrawBridge(OBJECT_INFO *obj);
+void Bridge_Initialise(int16_t item_num);
```
Comment (rr-) [inline src/game/objects/general/bridge.h:12]: nitpick: \n before to detach from the group of setup function declarations

File: src/game/objects/general/bridge.c [hunk 7]
```diff
@@ -223,3 +252,11 @@ void Bridge_Tilt2Ceiling(
...
     }
 }
+
+void Bridge_Initialise(int16_t item_num)
+{
+    // Some bridges at floor level are embedded into the floor.
+    // This checks if bridges are below a room's floor level
+    // and moves them up.
+    Bridge_FixEmbeddedPosition(item_num);
+}
```
Comment (rr-) [inline src/game/objects/general/bridge.c]: Nitpick: let's put it in an order that matches the header file (e.g. after setup draw bridge function)

**Review by rr- — APPROVED** [review]
2 remarks left, after they're tackled OK to merge :)

File: src/game/objects/general/bridge.c (hunk 7 above)
Comment (walkawayy) [reply src/game/objects/general/bridge.c]: I am NOT (!) suggesting we do anything since it's all cosmetic, but I did notice a lot of the .h files do not follow the function order in the .c file. I agree it should match lol. Maybe some time (far) into the future lol.

**Comment by walkawayy** [comment]
Oops just noticed you said to merge it after those are done. Going for it...

File: src/game/objects/general/bridge.c (hunk 7 above)
Comment (rr-) [reply src/game/objects/general/bridge.c]: I agree these need fixing. We'll get there, at some point. Looking forward to it :D
