### PR TITLE
tr1/lara/cheat: reset meshes in fly cheat

### LINKED ISSUE #2565: TR1X bug: Lara's model doesn't reset if resurrected after being eaten by the trex
**Regression since:** [4.8](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.8)

__________________

Image

**Edit:** I think this bug happens in all cases of Lara getting killed, not just death by trex.

For example, have Lara draw magnums, then reduce her hp to 0 and resurrect.

### LINKED ISSUE #2572: TR1X bug: Lara can end up with weapons in her hands
**Regression since:** [4.8](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.8)

_____________

1. `/play 1`
2. use the all weapons cheat
3. draw either pistols/shotgun/uzis/magnums
4. use the fly cheat, then immediately press shift to disable fly
5. Lara will have weapons in her hands

I think this issue was tackled in TR2X some time ago which is why it's not affected at this time.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #2565.
Resolves #2572.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This restores Lara's meshes if she is resurrected with the fly cheat. The only scenario we can't efficiently cover is the following:
- draw magnums or uzis
- draw shotgun
- die and resurrect

In this case the holstered guns will be pistols because we don't store the last holstered gun type, and looking it up would involve a lot of mesh comparison which I don't feel is worth it, plus for things like the T-Rex and Midas deaths, the information is lost anyway. If the last gun is not the shotgun, the correct holster meshes will be restored normally.

Otherwise, other scenarios should hopefully work as expected 🤞 Worth checking #2461 too.

### CODE REVIEW

**Comment by aredfan** [comment]
Everything looks good, thank you. 👍 

I did find a bug with Lara holding a shotgun in one hand, but I don't think it's related to this PR as it's already on develop, will raise an issue shortly.

**Review by aredfan — APPROVED** [review]

**Comment by lahm86** [comment]
> Everything looks good, thank you. 👍
> 
> I did find a bug with Lara holding a shotgun in one hand, but I don't think it's related to this PR as it's already on develop, will raise an issue shortly.

Thanks, should be addressed. Easiest just to do it here as it's all so related.

**Review by aredfan — APPROVED** [review]
> Thanks, should be addressed. Easiest just to do it here as it's all so related.

Your fix did the trick. Thank you. 😄

File: src/tr1/game/lara/cheat.c [hunk 1]
```diff
@@ -25,6 +26,39 @@
...
+
+    if (back_gun_type != LGT_UNARMED) {
+        Gun_SetLaraBackMesh(back_gun_type);
+    }
+
+    if (holsters_gun_type != LGT_UNARMED) {
+        Gun_SetLaraHolsterLMesh(holsters_gun_type);
+        Gun_SetLaraHolsterRMesh(holsters_gun_type);
+    }
+}
```
Comment (rr-) [inline src/tr1/game/lara/cheat.c]: This logic is duplicated from somewhere isn't it? I think Lara_InitialiseMeshes. Any chance we can avoid duplication?

Comment (lahm86) [reply src/tr1/game/lara/cheat.c]: Yeah, `Lara_InitialiseMeshes` uses `RESUME_INFO` though, so doesn't take into account guns she currently has, plus it results in the original bug with #2461. Maybe we could change the signature though.

**Review by rr- — APPROVED** [review]
LGTM but it'd be nice to merge the common parts, possibly through a new, third function.

**Comment by lahm86** [comment]
> LGTM but it'd be nice to merge the common parts, possibly through a new, third function.

WDYT about getting rid of `resume->flags.costume` in favour of just testing if it's currently the gym level? I think this would make it easier to merge the functions as we don't really need `RESUME_INFO`; Lara's inventory is already initialised on the only other call to `Savegame_ApplyLogicToCurrentInfo`.

**Comment by rr-** [comment]
> > LGTM but it'd be nice to merge the common parts, possibly through a new, third function.
> 
> WDYT about getting rid of `resume->flags.costume` in favour of just testing if it's currently the gym level? I think this would make it easier to merge the functions as we don't really need `RESUME_INFO`; Lara's inventory is already initialised on the only other call to `Savegame_ApplyLogicToCurrentInfo`.

This will make adding a potential option to change costumes at runtime more difficult; can we use a hybrid solution?

**Comment by lahm86** [comment]
Sure, I'll take another look tomorrow 👍

**Comment by lahm86** [comment]
Hybrid approach is now in place, so we just have a single function. This will need testing again I'm afraid, especially going between levels, and in Natla's Mines with gun loss. Also, going from the gym to a game level, or back to the gym via a save or otherwise, to ensure the costume swap behaves normally.

**Comment by aredfan** [comment]
> Hybrid approach is now in place, so we just have a single function. This will need testing again I'm afraid, especially going between levels, and in Natla's Mines with gun loss. Also, going from the gym to a game level, or back to the gym via a save or otherwise, to ensure the costume swap behaves normally.

These scenarios and the linked issues LGTM.

The only issue I found is that Lara's holstered weapons revert to pistols between levels if she has magnums/uzis holstered and the shotgun equipped.

**Comment by lahm86** [comment]
Thanks, @aredfan. Hopefully that's fixed now.

**Review by aredfan — APPROVED** [review]
> Thanks, @aredfan. Hopefully that's fixed now.

Can confirm, thank you. 👍

File: src/tr1/game/lara/common.c [hunk 2]
```diff
@@ -655,31 +655,41 @@ void Lara_RevertToPistolsIfNeeded(void)
...
+        Lara_SwapSingleMesh(
+            mesh, mesh == LM_HEAD || !use_costume ? O_LARA : O_LARA_EXTRA);
     }
 
-    LARA_GUN_TYPE holsters_gun_type =
-        resume != nullptr ? resume->holsters_gun_type : LGT_UNKNOWN;
-    LARA_GUN_TYPE back_gun_type =
-        resume != nullptr ? resume->back_gun_type : LGT_UNKNOWN;
+    LARA_GUN_TYPE back_gun_type = g_Lara.back_gun_type;
+    LARA_GUN_TYPE holsters_gun_type = g_Lara.holsters_gun_type;
```
Comment (rr-) [inline src/tr1/game/lara/common.c:667]: Is this swap ok with saved games? Eg having uzis holstered, saving, playing caves, and then loading the saved game will not revert the holstered guns back to pistols, right?

Comment (aredfan) [reply src/tr1/game/lara/common.c:667]: Yep, I can confirm that whichever weapon Lara has holstered/equipped is being loaded correctly.

E.g. If Lara has magnums/uzis holstered and shotgun equipped, it does not revert to pistols when saving and reloading.

**Review by walkawayy — APPROVED** [review]
