### PR TITLE
Fix sprite statics conflict

### LINKED ISSUE #2310: Sprite sequences cause weird meshes to appear
image
Seen in custom levels, originally reported by Brad on Discord.
TombEditor expands the static objects to pretend to be a part of the level geometry, but also leaves them hanging around in the room data so that they can still participate in collision tests. Later on, the sprite sequencer overrides this information with different meshes, causing the visual glitches shown above. The level looks fine inside TRView.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #2310.

#### Testing

- Look for missing static objects
- Look for missing sprites
- Check if animated sprites still work (the algae at the bottom of the Tihocan lake)
- TR1 and TR2

### CODE REVIEW

**Review by aredfan — APPROVED** [review]

File: src/tr1/game/level.c [hunk 1]
```diff
@@ -451,20 +459,31 @@ static void M_LoadSprites(VFILE *file)
...
-            object->mesh_count = num_meshes;
-            object->mesh_num = mesh_idx;
-            object->loaded = true;
+            STATIC_INFO *const object =
+                &g_StaticObjects[object_id - O_NUMBER_OF];
+            if (object->loaded) {
+                LOG_WARNING(
+                    "sprite %d is already loaded "
+                    "(trying to override %d:%d with %d:%d)",
+                    object_id - O_NUMBER_OF, object_id - O_NUMBER_OF,
```
Comment (lahm86) [inline src/tr1/game/level.c]: I think there is an extra `object_id - O_NUMBER_OF` here

File: src/tr2/game/level.c [hunk 2]
```diff
@@ -398,17 +410,31 @@ static void M_LoadSprites(VFILE *const file)
...
+            object->mesh_idx = mesh_idx;
             object->loaded = 1;
+        } else if (object_id - O_NUMBER_OF < MAX_STATIC_OBJECTS) {
+            STATIC_INFO *const object =
+                &g_StaticObjects[object_id - O_NUMBER_OF];
+            if (object->loaded) {
+                LOG_WARNING(
+                    "sprite %d is already loaded "
+                    "(trying to override %d:%d with %d:%d)",
+                    object_id - O_NUMBER_OF, object_id - O_NUMBER_OF,
```
Comment (lahm86) [inline src/tr2/game/level.c]: And here

File: src/tr1/game/level.c (hunk 1 above)
Comment (rr-) [reply src/tr1/game/level.c]: Good catch – fixed

**Review by lahm86 — APPROVED** [review]

**Comment by rr-** [comment]
I'll wait for Nickelony's response in TE Discord before merging.
