### PR TITLE
objects/flare_item: fix floor embedding

### LINKED ISSUE #3708: OG bug: flare can get stuck in the void if discarded while Lara is swimming/flying
Extracted from #1593 

_____________________________

The z-buffer setting will need to be disabled for this bug to be visible.

**Update:** The z-buffer option has been removed from TR2X since [1.4](https://github.com/LostArtefacts/TRX/releases/tag/tr2-1.4), thus the only method to view this bug is in photo mode.

This bug isn't present in TR3.

<details><summary>Video</summary>

https://github.com/user-attachments/assets/f2971f16-a82e-4af9-bea8-5f0212533864

</details>

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #3708.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/develop/docs/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This updates flare control to use the same collision detection as bouncing grenades, per OG TR3. It resolves flares falling through trapdoors and the OG bug in TR2 where they can become lodged in the void if thrown underwater near the floor.

### CODE REVIEW

File: src/trx/game/collision/common.c [hunk 1]
```diff
@@ -1085,8 +1085,43 @@ void Collide_DoProperDetection(ITEM *const item, const XYZ_32 old_pos)
...
+                item->pos.z,
+            };
+            room_num = item->room_num;
+            sector = Room_GetSector(test_pos, &room_num);
+            height = Room_GetHeight(sector, test_pos);
+            const bool on_walkable =
+                Room_IsOnWalkable(sector, test_pos, height, NO_ITEM);
+
+            if (item->pos.y >= height && on_walkable) {
+                if (item->fall_speed > 0) {
```
Comment (rr-) [inline src/trx/game/collision/common.c]: We can reduce nesting by moving this into inner `else`.

File: src/trx/game/collision/common.c [hunk 2]
```diff
@@ -1085,8 +1085,43 @@ void Collide_DoProperDetection(ITEM *const item, const XYZ_32 old_pos)
...
+                    if (item->fall_speed > 16) {
+                        if (item->object_id == O_GRENADE) {
+                            item->fall_speed =
+                                item->fall_speed / 2 - item->fall_speed;
+                        } else {
+                            item->fall_speed = -item->fall_speed / 2;
```
Comment (rr-) [inline src/trx/game/collision/common.c]: Aren't both branches the same except non-`O_GRENADE`s fall speeds get clamped?

File: src/trx/game/collision/common.c (hunk 1 above)
Comment (lahm86) [reply src/trx/game/collision/common.c]: Thanks.

File: src/trx/game/collision/common.c (hunk 2 above)
Comment (lahm86) [reply src/trx/game/collision/common.c]: Good catch, it was actually a porting bug. Fixed and tidied up.

**Review by rr- — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
