### PR TITLE
game: fix new saves not having the save count in the passport

### LINKED ISSUE #1591: OG bug: New save in an empty slot doesn't display the count
The save count won't display until after the game is restarted.

**Before:**

Screenshot 1

**After:**

Screenshot 2

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #1591.

Eventually this fix will be moved to S_SaveGame.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed new saves not displaying the save count in the passport. Will eventually move to the savegame functions once those are decompiled. Fix courtesy of rr.

### CODE REVIEW

**Review by rr- — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]

**Comment by aredfan** [comment]
Thank you for working on this bugfix. The savegame count is displaying properly when saving via the inventory or quick save, in an empty slot.

- [x] There's a small issue - if you use `/save x` in an empty slot, the bug persists.

**Comment by walkawayy** [comment]
@aredfan try now please.

File: src/tr2/game/savegame/common.c [hunk 1]
```diff
@@ -17,7 +17,11 @@ bool Savegame_IsSlotFree(const int32_t slot_idx)
 bool Savegame_Save(const int32_t slot_idx)
 {
     CreateSaveGameInfo();
+    const int16_t slot_num = g_Inv_ExtraData[1];
```
Comment (rr-) [inline src/tr2/game/savegame/common.c]: This duplicates `slot_idx`

**Review by rr- — APPROVED** [review]

**Comment by aredfan** [comment]
In the latest PR build - using the `/save` command for an empty slot still gives me this:

20241105_162354_The_Great_Wall

**Comment by walkawayy** [comment]
Hm are you sure you are on the latest build? I just double checked and it's working fine for me. Does the Github bot update the build? Here's my build info in the main menu:

image

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍
