### PR TITLE
gun/rifle: fix SFX, harpoon reload and grenade mesh frames

### LINKED ISSUE #3474: OG bug: incorrect animation when Lara withdraws the grenade launcher
When Lara withdraws the grenade launcher, the gun seems to delay switching from Lara's hand to her back so it remains in her hand a little too long.  The other rifle-type weapons are unaffected by this bug.

<details><summary>TR2 video</summary>

https://github.com/user-attachments/assets/20c03e7d-0235-4f79-bc09-1c969b8a1ac0

</details>

<details><summary>TR3 video, for reference</summary>

https://github.com/user-attachments/assets/43760a13-2b1b-48e0-a2af-791d54d89cec

</details>

### LINKED ISSUE #3755: OG bug: incorrect SFX used when drawing/holstering rifle-type weapons
In TR1, the `LARA_DRAW` sound effect plays when holstering the shotgun, and in TR2, the `LARA_HOLSTER` sound effect plays when drawing the shotgun, harpoon gun, M16, and grenade launcher.

### LINKED ISSUE #4259: OG bug: selecting harpoon when out of ammo causes reload animation
https://github.com/LostArtefacts/TRX/pull/4257#issuecomment-3484181366

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #4259.
Resolves #3474.
Resolves #3755.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

I've bundled these fixes together for easier testing - commits remain separate. Re the grenade launcher differences, I wondered about moving this information out into the weapons JSON, WDYT?

Ref: https://github.com/LostArtefacts/TRXInjectionTool/pull/155

### CODE REVIEW

**Review by aredfan — APPROVED** [review]
Thank you kindly for fixing Lara's grenade launcher anim. 👍

File: src/trx/game/gun/rifle.c [hunk 1]
```diff
@@ -30,9 +32,26 @@ typedef enum {
...
+static const M_ANIM_SETUP m_RegularSetup = {
+    .equip_anim_idx = 1,
+    .draw_frame = 10,
+    .undraw_frame = 21,
+};
+
+static const M_ANIM_SETUP m_GrenadeSetup = {
+    .equip_anim_idx = 0,
+    .draw_frame = 13,
+    .undraw_frame = 14,
```
Comment (rr-) [inline src/trx/game/gun/rifle.c:44]: Sounds good to ship this in json, yes.

**Review by rr- — APPROVED** [review]

File: src/trx/game/gun/rifle.c (hunk 1 above)
Comment (lahm86) [reply src/trx/game/gun/rifle.c:44]: Cool, I'll follow that up in a new PR and will add some docs for the weapons JSON (pointers for `is_available` and suchlike).
