### PR TITLE
output: sort skybox faces and flush after drawing

### LINKED ISSUE #4351: TRX bug: transparent faces in skyboxes are drawn in front of all other faces
If a skybox has inner faces to simulate depth e.g. a line of trees, and the faces contain transparent pixels, those faces will always render above all rooms and objects in view.
Will share a test level on Discord.
Issue noted by Lore. Regression from 1.0.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #4351.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This allows skyboxes to have transparent (or blended) faces and to take part in sorting. The scene is flushed immediately after staging.

I'll follow this up with a change we discussed a while ago to use the skybox flag in TR1 rooms similar to TR2+, rather than always drawing it when it's loaded.

### CODE REVIEW

**Review by aredfan — APPROVED** [review]

File: src/trx/game/output/mesh_batcher/batcher.c [hunk 1]
```diff
@@ -416,7 +416,7 @@ static void M_RenderPass(
 {
     MESH_BATCHER *const batcher = source->priv;
 
-    if (pass == SCENE_PASS_OPAQUE || pass == SCENE_PASS_SKYBOX) {
+    if (pass == SCENE_PASS_OPAQUE) {
         M_OpaquePass(batcher, pass);
```
Comment (rr-) [inline src/trx/game/output/mesh_batcher/batcher.c]: No longer needed to pass the `pass` argument - all opaque steps can be simplified in this module now

File: src/trx/game/output/sources/objects.c [hunk 2]
```diff
@@ -224,13 +224,9 @@ static void M_Stage(const OBJECT_MESH *const mesh, const bool skybox)
         },
         .room = Output_GetCurrentRoom(),
     };
-    if (skybox) {
```
Comment (rr-) [inline src/trx/game/output/sources/objects.c:227]: The skybox argument can likely be removed now?

File: src/trx/game/output/mesh_batcher/batcher.c (hunk 1 above)
Comment (lahm86) [reply src/trx/game/output/mesh_batcher/batcher.c]: Thanks, updated.

File: src/trx/game/output/sources/objects.c (hunk 2 above)
Comment (lahm86) [reply src/trx/game/output/sources/objects.c:227]: Updated 😌

**Review by rr- — APPROVED** [review]
