### PR TITLE
Fix shattering windows

### LINKED ISSUE #3378: OG bug: possible for projectiles to do no damage to breakable windows
This bug depends on the breakable window's position. If a window is positioned in the middle of a tile, it can be broken by projectiles from both directions (e.g. Venice). Whereas if a window is positioned on the edge of a tile, it can only be broken from one side (e.g. Offshore Rig). Perhaps the portals have something to do with it.

<details><summary>TR2 levels of interest</summary>

- Lara's Home (with cheats)
- Offshore Rig
- Tibetan Foothills
- Home Sweet Home (with cheats)
- The Cold War

</details>

<details><summary>TR3 levels of interest</summary>

- Area 51
- All Hallows
- Shakespeare Cliff

</details>

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #3378.

### CODE REVIEW

File: src/tr2/game/gun/gun_misc.c [hunk 1]
```diff
@@ -179,17 +196,28 @@ int32_t Gun_FireWeapon(
...
             target, &hit_pos,
             winfo->damage * (Game_IsBonusFlagSet(GBF_JAPANESE) ? 2 : 1));
         return 1;
     }
 }
 
+bool Gun_SmashItems(const GAME_VECTOR start, const GAME_VECTOR target)
+{
+    bool broken = false;
+    while (true) {
```
Comment (lahm86) [inline src/tr2/game/gun/gun_misc.c:211]: In Ice Palace, shooting the bell causes an infinite loop here. This seems to resolve it, but perhaps there is a better way.

```diff
diff --git a/src/tr2/game/los.c b/src/tr2/game/los.c
index a47787d4a..04917dc0b 100644
--- a/src/tr2/game/los.c
+++ b/src/tr2/game/los.c
@@ -307,7 +307,8 @@ int32_t LOS_CheckSmashable(
 
     for (int16_t item_num = 0; item_num < Item_GetTotalCount(); item_num++) {
         const ITEM *const item = Item_Get(item_num);
-        if (item->status == IS_DEACTIVATED) {
+        if (item->status == IS_DEACTIVATED
+            || (item->object_id == O_BELL && item->status == IS_ACTIVE)) {
             continue;
         }
         if (!Object_IsType(item->object_id, g_SmashableObjects)) {
```

Comment (rr-) [reply src/tr2/game/gun/gun_misc.c:211]: Added a check in `Gun_SmashItems`

**Comment by rr-** [comment]
Added additional improvement to avoid shattering windows placed behind bells. Adjacent windows will still be shatterable all at once.

**Review by lahm86 — APPROVED** [review]

**Comment by aredfan** [comment]
Thank you for working on this PR, it works well with the test level. 👍 

I'm afraid the bug from the issue does persist, I probably didn't do a good job of explaining it.  The issue is there are some windows positioned on the edge of a tile which results in Lara's projectiles breaking the windows only from one side.  A good place to test this is in offshore rig, room 3.  If you have Lara shoot the harpoon gun from within the room, then again from the other side of the breakable windows.

**Comment by rr-** [comment]
@aredfan got it. In this PR I focused on normal weapons which had the same problem. I could've swear I've seen a separate issue targeting harpoon and grenade projectiles.

**Comment by rr-** [comment]
Since harpoons and grenades both use very different code routines, can we make it a different ticket?

**Review by aredfan — APPROVED** [review]
> Since harpoons and grenades both use very different code routines, can we make it a different ticket?

Yes, that's no problem at all.  I'll raise an issue in a bit.
