### PR TITLE
tr2/music_main: refactor music track handling

### LINKED ISSUE #1899: TR2X bug: some music triggers loop and others don't repeat
An example is the trigger at the zip line in Great Wall. Although the trigger isn't one-shot, in OG it only plays once if you stand on the tile, whereas in TR2X it loops until you move away.
One-shot music triggers behave fine.

Another issue is if you complete the assault course and get a best time, then complete and beat the time again without triggering any other music tracks, Lara does not repeat the "best time yet" line at the end.

Regression from 0.2.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #1899.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This refactors the way music is checked when requested to play tracks. We introduce tracking, similar to TR1 - I think prior to 0.2, it was implicitly done by setting (or not setting) `g_CD_TrackID` before playing the music in various places, so it was difficult to keep track of that. That global is now redundant, although remains in place, along with the original `Music_Play` function (renamed).

Some tracks require to be enforced such as from flip effects (like completing the assault course) and mounting the skidoo. Tracked trigger tracks will not play in succession, provided the mode is the same when requesting to play them. So standing on a tile doesn't loop a track.

Attached is a test level which should behave the same played in OG as TR2X. So e.g. if you cross the "manual" secret track trigger, then collect a secret, the track will restart (similarly if you collect the secrets quickly before the track finishes each time). And if you cross the skidoo track trigger, then mount the skidoo itself, the music will restart, the same as OG. On the other foot, if you mount the skidoo first, wait for the track to completely finish, then cross the trigger for the same track, it doesn't play.

The assault course is a good place to test everything too, especially the delayed tracks there and ensuring Lara acknowledges beating the best time twice in a row. The test level can also be renamed to `boat.tr2` to check a level with no ambience. Renaming it to `house.tr2` will allow for example triggering the skidoo music, then ending the level, and ensuring the credits restart the track.

[WALL.zip](https://github.com/user-attachments/files/17781058/WALL.zip)

### CODE REVIEW

File: src/tr2/global/vars_decomp.h [hunk 1]
```diff
@@ -12,7 +12,7 @@
 #define g_RhwFactor (*(float*)0x0046408C) // = 335544320.0f
 #define g_CineTrackID (*(int32_t*)0x004640B0) // = 1
 #define g_CineTickRate (*(int32_t*)0x004640B8) // = 0x8000
-#define g_CD_TrackID (*(int16_t*)0x004640BC) // = -1
+#define g_Legacy_CD_TrackID (*(int16_t*)0x004640BC) // = -1
```
Comment (rr-) [inline src/tr2/global/vars_decomp.h]: Hi, this file is updated by progress.txt as well. Let's mark this variable with a `+` flag in progress.txt (without renaming it). This way, it'll be visible as `g_CD_TrackID` in IDA, while it'll be completely skipped in our codebase.

As for `Music_Legacy_Play`, we can safely remove its definitions altogether, considering how since 0.2 we're no longer trying to inject it (and thus are free to use our own signatures).

After these changes please make sure to run `tools/tr2/generate_funcs` to see all is compatible.
Apologies for not documenting this process better, but hopefully it won't be long until we can start freely refactoring the majority of the codebase.

Comment (lahm86) [reply src/tr2/global/vars_decomp.h]: Thank you, and no - my apologies for not getting this bit right.

I've changed the variable back to OG and marked it as decompiled.

The legacy function is still in use though: below is with logging added, it's triggered when Lara completes the assault course (possibly elsewhere, but this one for sure). I'm assuming that flip effect does some comparison with the player's time and decides which track to play (22 is "gosh, that was my best time yet").

```
game/music/music_main.c 116 Music_Legacy_Play Legacy call for track: 22
game/music/music_main.c 149 Music_Play Playing track 22 (real: 19), mode: 0
```

image

**Review by aredfan — APPROVED** [review]

**Review by rr- — APPROVED** [review]
