### PR TITLE
tr2/savegame: fix SAVEGAME_INFO layout I/O

### LINKED ISSUE #2271: TR2X bug: secrets found and health packs used is incorrect when loading a TR2X save in OG
**Regression since:** [0.8](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.8)

_____________________________

**Steps:**

1. `/play 1`
2. `/tp sec`
3. pick up the secret
4. `/save 1`
5. load the save in OG and view the stats

**TR2X:**
20250112_164553_The_Great_Wall

**OG:**
Screenshot

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #2271.

#### Testing

General savegame quick checks.

- statistics (including final stats taking into account stats from completed levels)
- inventory (guns, ammo, pickups, flares)
- NG+ flag
- starting gun

There is more than the above to the savegames, but we've not touched much beyond what I listed above.

### CODE REVIEW

File: src/tr2/decomp/savegame.c [hunk 1]
```diff
@@ -942,8 +1048,8 @@ int32_t S_SaveGame(
     return true;
 }
 
-int32_t S_LoadGame(
-    void *const save_data, const size_t save_size, const int32_t slot_num)
+#include <libtrx/log.h>
```
Comment (lahm86) [inline src/tr2/decomp/savegame.c]: Do you want to retain the logging here for now?

Comment (rr-) [reply src/tr2/decomp/savegame.c]: Oh no, I'll get rid of it right away.

Comment (rr-) [reply src/tr2/decomp/savegame.c]: Done

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍 

The only anomaly I could find is flares show a count of 255 in NG+, but the issue is present in the latest dev snapshot.

**Review by lahm86 — APPROVED** [review]
