### PR TITLE
overlay: change bars to better match PS1 and fix scaling options

### LINKED ISSUE #698: Reinstate classic health and air bar style
Apologies in advance for posting something so nitpicky and annoyingly "purist", but I still cant help notice this after all this time.

If…
```json5
"enable_smooth_bars" : false,
```
…could I ask to have the authentic PS1 health and air bar style be reinstated?

When TR1M came out I thought this was just a case of having to find the right bar scaling, but I could never reproduce the same classic look.

I looked into it a bit more, and the differences are of course rather marginal:
- bigger grey border
- no bevel effect in the border
- bigger black padding inside the border
- the 5 colours making the gradient are slightly different to what TR1M uses, and each in equal height

Health Bar

Air Bar

It just feels to me that if someone chooses to not use the smooth bars, they should nail the classic look.

Thanks for considering.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #698.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/rr-/Tomb1Main/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Changed the health, air, and enemy bars to better match the PS1 version. Fixed the health, air, and enemy bars from being affected by the text scaling option,
...

### CODE REVIEW

File: src/game/screen.c [hunk 1]
```diff
@@ -96,6 +106,21 @@ int32_t Screen_GetRenderScale(int32_t unit)
     return MIN(scale_x, scale_y);
 }
 
+int32_t Screen_GetRenderScaleBar(int32_t unit)
+{
+    int32_t baseWidth = 640;
+    int32_t baseHeight = 480;
```
Comment (rr-) [inline src/game/screen.c]: Can we fix this naming convention while we're at it? In both functions.

File: src/game/screen.c [hunk 2]
```diff
@@ -96,6 +106,21 @@ int32_t Screen_GetRenderScale(int32_t unit)
...
+    int32_t scale_x = Screen_GetResWidth() > baseWidth
+        ? ((double)Screen_GetResWidth() * unit * g_Config.ui.bar_scale)
+            / baseWidth
+        : unit * g_Config.ui.bar_scale;
+    int32_t scale_y = Screen_GetResHeight() > baseHeight
+        ? ((double)Screen_GetResHeight() * unit * g_Config.ui.bar_scale)
+            / baseHeight
+        : unit * g_Config.ui.bar_scale;
+    return MIN(scale_x, scale_y);
+}
```
Comment (rr-) [inline src/game/screen.c:114]: These two functions are practically identical. I suggest to refactor things a bit:

```c
int32_t Screen_GetRenderScaleBase(
    int32_t unit, int32_t base_width, int32_t base_height, double factor
) {
￼    int32_t scale_x = Screen_GetResWidth() > base_width
￼        ? ((double)Screen_GetResWidth() * unit * factor)
￼            / base_width
￼        : unit * factor;
￼    int32_t scale_y = Screen_GetResHeight() > base_height
￼        ? ((double)Screen_GetResHeight() * unit * factor)
￼            / base_height
￼        : unit * factor;
￼    return MIN(scale_x, scale_y);
}

int32_t Screen_GetRenderScaleText(int32_t unit) {
    return Screen_GetRenderScaleBase(unit, 640, 480, g_Config.ui.text_scale);
}

int32_t Screen_GetRenderScaleBar(int32_t unit) {
    return Screen_GetRenderScaleBase(unit, 640, 480, g_Config.ui.bar_scale);
}
```

and replace `Screen_GetRenderScale` usages with `Screen_GetRenderScaleText`.

File: src/game/screen.h [hunk 3]
```diff
@@ -11,13 +11,16 @@ int32_t Screen_GetResIdx(void);
 int32_t Screen_GetResWidth(void);
 int32_t Screen_GetResHeight(void);
 int32_t Screen_GetResWidthDownscaled(void);
+int32_t Screen_GetResWidthDownscaledBar(void);
```
Comment (rr-) [inline src/game/screen.h:15]: If you agree with my other suggestion we should rename `Screen_GetResWidthDownscaled` to `Screen_GetResWidthDownscaledText` as well for consistency.

Comment (walkawayy) [reply src/game/screen.h:15]: Ok I'll refactor a little. I didn't want to do it yet in case you didn't want to.

**Comment by walkawayy** [comment]
Here's a video showing some different combinations of text/bar scaling. I think 2.0 scaling is definitely ridiculous lol. Lmk if we wanna cap it at 1.5 or so.

https://www.youtube.com/watch?v=o_bxKSqZp30

And here's an example showing the behavior will work with the enemy health bar also in the top right.

https://www.youtube.com/watch?v=RiIP47ESseg

**Comment by walkawayy** [comment]
Here's a test build. Called it v3.1 since it's just some code refactoring.

[Tomb1Main Classic Bars v3-1.zip](https://github.com/LostArtefacts/Tomb1Main/files/11052957/Tomb1Main.Classic.Bars.v3-1.zip)

**Comment by Richard-L** [comment]
Very nice tests.

It looks like the gap between bar and ammo count+icon depends on bar scale. Had this better been independent perhaps? You see in your Text x2, Bar x.5 example, the ammo icon touches the bottom of the bar because no gap is left.
The reverse also happens in the other extreme (Text x.5, Bar x2), where then there is too much gap under the bar.

How is the gap calculated atm?

The enemy bar in the same spot is quite misleading if you ask me, as it looks so similar to the air bar in this particular colour, but I guess the user might set this. Almost makes me think if the config tool would ideally ask about bar positions in concession, where health and air come first, and then enemy bars cannot be placed in the same spot to avoid this confusion.

One other thing I notice: if you have weapons equipped and jump into water, the health bar immediately transforms into an air bar.

https://user-images.githubusercontent.com/4934209/227374017-41dc9306-62b8-4e32-9982-abb2f23f4501.mp4

Would this speak in favour of fixed separate positions for both bars for added clarity?

**Comment by walkawayy** [comment]
The bars and text have completely different scaling options. I tried to make it so mixing and matching them dynamically yields good results. Which I think it does.

`The enemy bar in the same spot is quite misleading if you ask me, as it looks so similar to the air bar in this particular colour, but I guess the user might set this.` Yes I only tested that to make sure nothing overlaps incorrectly. The user can configure that, but I'd guess almost no one will. And it's definitely not a default setting.

I don't think the video you posted is any reason to change anything. Having fixed positions for the bars just wastes screen real estate IMO. The default colors are different enough to avoid confusion.

**Comment by rr-** [comment]
Let's cap the bar scales at 1.5.

The gap is negligible because nobody's gonna play with this combination, and it'll be gone after we cap the scale at 1.5, so this can be dismissed.

PS1 fixed placement stems from lazy coding and is just aesthetically unpleasing. The bars are distinguishble enough with the colors like walkawayy said. The bar placement is to remain dynamic.

**Comment by walkawayy** [comment]
Lmk if this is ok. Or I can make separate `MIN_TEXT_SCALE .5f` and `MIN_BAR_SCALE .5f` constants.

File: src/game/overlay.c [hunk 4]
```diff
@@ -400,12 +395,20 @@ void Overlay_RemoveAmmoText(void)
...
+    const int32_t screen_margin_h = 24;
     const int32_t screen_margin_v = 18;
 
+    // Scale ammo string properly if text scaling used.
+    double scale_ammo_to_bar = g_Config.ui.bar_scale;
+    if (g_Config.ui.text_scale > 1) {
+        scale_ammo_to_bar /= g_Config.ui.text_scale;
+    } else if (g_Config.ui.text_scale < 1) {
+        scale_ammo_to_bar *= 1 / g_Config.ui.text_scale;
+    }
```
Comment (rr-) [inline src/game/overlay.c]: Wait, how are these two operations different? (Is `1` getting promoted to a double `1.0`?)

File: src/global/const.h [hunk 5]
```diff
@@ -11,7 +11,8 @@
 #define PHD_135 (PHD_45 * 3) // = 24576 = 0x6000
 
 #define MIN_UI_SCALE 0.5f
-#define MAX_UI_SCALE 2.0f
+#define MAX_TEXT_SCALE 2.0f
+#define MAX_BAR_SCALE 1.5f
```
Comment (rr-) [inline src/global/const.h]: Let's make these a `double` by removing the `f `suffix.

File: src/game/overlay.c (hunk 4 above)
Comment (walkawayy) [reply src/game/overlay.c]: Oops you are right these are the same. I was testing some different formulas lol. I'll do:
```
// Scale ammo string properly if text scaling used.
double scale_ammo_to_bar = g_Config.ui.bar_scale / g_Config.ui.text_scale;
```

File: src/global/const.h (hunk 5 above)
Comment (walkawayy) [reply src/global/const.h]: Maybe they should be floats and I should change all the use cases to float:
```
    struct {
        double text_scale;
        double bar_scale;
        UI_STYLE menu_style;
    } ui;
```
?

That would match:
```
#define MIN_BRIGHTNESS 0.1f
#define MAX_BRIGHTNESS 2.0f
#define DEFAULT_BRIGHTNESS 1.0f
```

And they are read in `config.c` as floats:
```
    READ_FLOAT(ui.text_scale, DEFAULT_UI_SCALE);
    CLAMP(g_Config.ui.text_scale, MIN_UI_SCALE, MAX_TEXT_SCALE);
```

Also lmk if I should make separate `MIN_TEXT_SCALE .5f` and `MIN_BAR_SCALE .5f` constants.

Comment (rr-) [reply src/global/const.h]: Let's leave it as double. `READ_FLOAT` is actually ill-formed because it returns doubles:

```c
#define READ_FLOAT(opt, default_value)
    READ_PRIMITIVE(json_object_get_double, opt, default_value)
```

but let's not touch that here.

As for the constants, at first I liked the current way, but you're right, it'll be more consistent to have separate constants for the minimum values so let's go with your suggestion.

**Review by rr- — APPROVED** [review]
