### PR TITLE
tr1/savegame: fix issue with drawing weapons

### LINKED ISSUE #3844: TR1 Can't pull the gun out
After entering the level, pressing the space bar doesn't enable the gun.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #3844.

### CODE REVIEW

File: src/libtrx/game/gun/control.c [hunk 1]
```diff
@@ -157,6 +157,9 @@ static void M_DecideRequestedWeapon(void)
     LARA_INFO *const lara = Lara_GetLaraInfo();
     const ITEM *const lara_item = Lara_GetItem();
     if (g_Input.draw) {
+        if (lara->last_gun_type == LGT_UNARMED) {
```
Comment (lahm86) [inline src/libtrx/game/gun/control.c]: Might be worth adding an inventory check that Lara has pistols. On this build you can do the following:

- `/play 13`
- `/fly`
- press draw input
- exit fly cheat
- Lara now has pistols in her holsters, but not inventory

Similar in HSH and when you then pickup the shotgun, pressing draw has no effect.

Comment (rr-) [reply src/libtrx/game/gun/control.c]: >Similar in HSH and when you then pickup the shotgun, pressing draw has no effect.

Is this an OG behavior or TRX bug?

Comment (lahm86) [reply src/libtrx/game/gun/control.c]: TRX, but only this build - develop is OK.

Comment (rr-) [reply src/libtrx/game/gun/control.c]: Fixed (though unsure whether the changelog needs an update)

**Review by aredfan — APPROVED** [review]

File: src/libtrx/game/gun/control.c (hunk 1 above)
Comment (lahm86) [reply src/libtrx/game/gun/control.c]: Changelog looks good to me 😌

**Review by lahm86 — APPROVED** [review]
