### PR TITLE
tr2: fix misc config issues

### LINKED ISSUE #2830: TR2X bug: controls layout reverts to default regardless of changing to other layouts
**Regression since:** [1.0](https://github.com/LostArtefacts/TRX/releases/tag/tr2-1.0)

### LINKED ISSUE #2831: TR2X bug: use psx fov doesn't toggle on the fly
**Regression since:** [1.0](https://github.com/LostArtefacts/TRX/releases/tag/tr2-1.0)

### LINKED ISSUE #2832: TR2X bug: aspect ratio changes doesn't re-pick the correct designated background on the fly
**Regression since:** [1.0](https://github.com/LostArtefacts/TRX/releases/tag/tr2-1.0)

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #2830.
Resolves #2831.
Resolves #2832.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

I've bundled these together as they're somewhat similar, commits remain separate.

### CODE REVIEW

**Review by aredfan — APPROVED** [review]

File: src/tr2/game/shell/common.c [hunk 1]
```diff
@@ -424,9 +424,13 @@ static void M_HandleConfigChange(const EVENT *const event, void *const data)
 
     if (CHANGED(visuals.fog_start) || CHANGED(visuals.fog_end)
         || CHANGED(visuals.water_color.g) || CHANGED(visuals.water_color.b)
-        || CHANGED(visuals.water_color.r)) {
+        || CHANGED(visuals.water_color.r) || CHANGED(visuals.use_psx_fov)) {
```
Comment (rr-) [inline src/tr2/game/shell/common.c]: Rather than doing it for this check can we bundle it with the biggest one that does the M_ResetRendererViewport?

Comment (lahm86) [reply src/tr2/game/shell/common.c]: Thanks, updated.

**Review by aredfan — APPROVED** [review]

**Review by rr- — APPROVED** [review]
