### PR TITLE
shell: rework gameflow options to fix high numbered savegames

### LINKED ISSUE #1395: Savegame slots over 64 are unusable
Investigated by Lahm:

```
So the limit is 64 slots, and it's because of this 
int32_t gf_param = gf_option & ((1 << 6) - 1);
e.g. stemming from return GF_START_SAVED_GAME | g_GameInfo.current_save_slot in the inventory
https://github.com/LostArtefacts/TR1X/blob/develop/src/game/shell.c#L187

Hit 65, and it loops back to slot 1.
```

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #1395.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed savegame slots higher than 64 not working. Third and final part of breaking #1389 up into separate PRs.

EDIT: Bugfix in f44cbcf.

### CODE REVIEW

File: src/game/game/game.c [hunk 1]
```diff
@@ -202,21 +206,42 @@ GAMEFLOW_OPTION Game_Stop(void)
     if (g_LevelComplete) {
         // TODO: why is this made unavailable?
         g_GameInfo.current[g_CurrentLevel].flags.available = 0;
-        return GF_LEVEL_COMPLETE | g_GameInfo.select_level_num;
+        return (GAMEFLOW_INSTRUCTION) {
+            .instruction = GF_LEVEL_COMPLETE,
+            .param = g_GameInfo.select_level_num,
```
Comment (walkawayy) [inline src/game/game/game.c:210]: I'm confused what is going on here with `select_level_num`. This function is kinda confusing overall, but I left it alone since it's working and it's unrelated to this PR.

File: src/game/game/game.c [hunk 2]
```diff
@@ -202,21 +205,42 @@ GAMEFLOW_OPTION Game_Stop(void)
...
-        return GF_START_GAME | g_GameFlow.first_level_num;
+        return (GAMEFLOW_INSTRUCTION) {
+            .instruction = GF_START_GAME,
+            .param = g_GameFlow.first_level_num,
+        };
     } else {
-        return GF_EXIT_TO_TITLE;
+        return (GAMEFLOW_INSTRUCTION) {
+            .instruction = GF_EXIT_TO_TITLE,
+            .param = g_GameInfo.select_level_num,
```
Comment (rr-) [inline src/game/game/game.c]: Let's leave the `.param` as `0` if it's unused.

File: src/game/phase/phase.c [hunk 3]
```diff
@@ -25,23 +25,28 @@ static bool m_Running = false;
...
+static GAMEFLOW_INSTRUCTION Phase_Control(int32_t nframes)
 {
     if (g_GameInfo.override_option != GF_PHASE_CONTINUE) {
-        const GAMEFLOW_OPTION result = g_GameInfo.override_option;
         g_GameInfo.override_option = GF_PHASE_CONTINUE;
-        return result;
+        return (GAMEFLOW_INSTRUCTION) {
+            .instruction = g_GameInfo.override_option,
+            .param = 0,
+        };
```
Comment (rr-) [inline src/game/phase/phase.c:41]: Oh no! You return `GF_PHASE_CONTINUE` here but the idea is to use the value prior to setting it!

File: src/global/types.h [hunk 4]
```diff
@@ -960,19 +960,24 @@ typedef enum GAMEFLOW_OPTION {
...
+    GF_START_FMV = 2,
+    GF_START_DEMO = 3,
+    GF_EXIT_TO_TITLE = 4,
+    GF_LEVEL_COMPLETE = 5,
+    GF_EXIT_GAME = 6,
+    GF_START_SAVED_GAME = 7,
+    GF_RESTART_GAME = 8,
+    GF_SELECT_GAME = 9,
+    GF_START_GYM = 10,
+    GF_STORY_SO_FAR = 11,
```
Comment (walkawayy) [inline src/global/types.h]: I'll remove the integers tomorrow.

Comment (rr-) [inline src/global/types.h]: We can remove hardcoded numeric assignments since these numbers are only used internally.

File: src/global/types.h [hunk 5]
```diff
@@ -960,19 +960,24 @@ typedef enum GAMEFLOW_OPTION {
...
 } GAMEFLOW_OPTION;
 
+typedef struct GAMEFLOW_INSTRUCTION {
+    GAMEFLOW_OPTION instruction;
+    int32_t param;
+} GAMEFLOW_INSTRUCTION;
```
Comment (rr-) [inline src/global/types.h]: I wonder if it's possible to shorten this name somehow. The only proposal that comes to my mind is `GAMEFLOW_COMMAND`, and it'd be nice, if it wasn't for a naming conflict with the console commands. WDYT?

**Review by rr- — COMMENTED** [review]
Thanks. This looks great.

**Review by rr- — APPROVED** [review]
