### PR TITLE
items/actions: move to catalogs, merge in TRX

### LINKED ISSUE #4085: OG bug: triggering certain flip effects can cause a crash
E.g. flip effect 0 expects to be called from an animation command to do the turn 180 action on an item, but it's technically valid to put a floor trigger in place with this effect number. This leads to a crash as there is no item in this scenario. Flip effects like this should be guarded with null checks.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #4085.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Item actions (flip effects) are now using catalogs and have been merged in TRX, meaning they can be shared between games.

We'll need to test all the effects I'm afraid:

Common
- Flip 180
- Finish level (Larson, Sanctuary scion, Bird Monster)
- Lara hands free e.g. after pulling up on a ledge, she should be able to draw guns, or use her hands again
- Lara "normal" - e.g. after picking up the Qualopec scion, she returns to normal
- Lara drawing guns in cutscenes - hand and leg meshes should update
- Lara's bubbles underwater
- Flood "whoosh" - Cistern/40 Fathoms
- Floor shake e.g. T-rex, pushblock hitting ground

TR1
- Tihocan chainblock (note the config option to fix the SFX is now in TR2 as well, but hidden)
- Atlantis start flickering
- Midas raising block room SFX
- Stairs-to-slope in Obelisk
- Dropping sand in Khamoon
- Mines explosion (after the cowboy)

TR2
- Assault course reset, stop, start and finish
- Bartoli's chandelier SFX
- 40F massive crash
- Wreck engine room flip map SFX
- Living Quarters piston SFX
- Living Quarters stage curtain SFX
- Barkhang statue SFX (room 55)
- Cutscene actors
  - Dynamic light (GW gunshots)
  - Invisibility - used in GW cut to swap the cultist to the same model with a poison bottle in his hand (I don't know why mesh swap isn't used for this)
  - Mesh swaps - Diving Area Lara outfit, Bartoli in Xian

### CODE REVIEW

File: src/libtrx/game/items/actions/common.c [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+    Item_ActionRun(trx_id, item);
+}
+
+void Item_ActionRunActive(void)
+{
+    const int32_t flip_effect = Room_GetFlipEffect();
+    if (flip_effect != -1) {
+        Item_ActionRunDirect(flip_effect, nullptr);
+    }
+}
```
Comment (rr-) [inline src/libtrx/game/items/actions/common.c:32]: WDYT of naming this namespace `ItemAction_*` rather than `Item_Action*`?

**Review by rr- — APPROVED** [review]
🩷

File: src/libtrx/game/items/actions/common.c (hunk 1 above)
Comment (lahm86) [reply src/libtrx/game/items/actions/common.c:32]: Sure, no problem, I'll update that.

**Review by rr- — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
