### PR TITLE
creature: restore death state based on type ID

### LINKED ISSUE #2960: TR1X bug: dead voles revert after saving and reloading
Regression since [0.12](https://github.com/LostArtefacts/TRX/releases/tag/tr1-0.12.0)

1. download the attached save [save_tr1_00.zip](https://github.com/user-attachments/files/20081430/save_tr1_00.zip)
2. kill the nearby vole
3. `/save 2`
4. `/load 2`
5. also try `/flip` after reloading for good measure

Image

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #2960.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This ensures that post-load, a hybrid creature's correct state is reinstated. The savegame will have stored the state and animation against the original type ID in the level, but we need to infer the actual type ID on load.

### CODE REVIEW

**Comment by lahm86** [comment]
I think these are all the scenarios, so we'll need to check save/load and regular flip behaviour. I'll share a test level as I don't think there's an OG level with a vole in a room that can be drained (and saved in that state).

| Creature | State | Room | Pass/Fail |
|-|-|-|-|
| Rat | Alive | Drained | ✅ |
| Rat | Dead | Drained | ✅ |
| Vole | Alive | Drained | ✅ |
| Vole | Dead | Drained | ✅ |
| Rat | Alive | Flooded | ✅ |
| Rat | Dead | Flooded | ✅ |
| Vole | Alive | Flooded | ✅ |
| Vole | Dead | Flooded | ✅ |
| Crocodile | Alive | Drained | ✅ |
| Crocodile | Dead | Drained | ✅ |
| Alligator | Alive | Drained | ✅ |
| Alligator | Dead | Drained | ✅ |
| Crocodile | Alive | Flooded | ✅ |
| Crocodile | Dead | Flooded | ✅ |
| Alligator | Alive | Flooded | ✅ |
| Alligator | Dead | Flooded | ✅ |

**Comment by aredfan** [comment]
The rats and voles LGTM. 👍 

I noticed a couple of issues which isn't present in develop.

- [x] The crocodile remains on the floor of a flooded room with these steps:

1. play the test level
2. cross the crocodile trigger
3. `/save 1`
4. `/load 1`

- [x] The alligator can escape from the pit with these steps:

1. play the test level
2. cross the alligator trigger
3. cross the flip map trigger
4. `/save 1`
5. `/load 1`

File: src/tr1/game/objects/creatures/rat.c [hunk 1]
```diff
@@ -208,15 +220,8 @@ static void M_ControlVole(const int16_t item_num)
...
-            item->pos.x, item->pos.y, item->pos.z, item->room_num);
-        if (wh == NO_HEIGHT) {
-            item->object_id = O_RAT;
-            item->current_anim_state = RAT_STATE_DEATH;
-            item->goal_anim_state = RAT_STATE_DEATH;
-            Item_SwitchToAnim(item, RAT_DIE_ANIM, -1);
-            item->pos.y = item->floor;
-        }
+        int32_t water_height;
+        Creature_EnsureHabitat(item_num, &water_height, &m_RatInfo);
```
Comment (rr-) [inline src/tr1/game/objects/creatures/rat.c]: Wdyt about making water height a nullptr for those cases?

**Review by rr- — APPROVED** [review]

File: src/tr1/game/objects/creatures/rat.c (hunk 1 above)
Comment (lahm86) [reply src/tr1/game/objects/creatures/rat.c]: Thanks, done.

**Comment by lahm86** [comment]
Thanks, @aredfan. I had failed to reset the pathfinding values which was the cause of both issues, should hopefully be behaving now.

**Review by aredfan — APPROVED** [review]
> Thanks, @aredfan. I had failed to reset the pathfinding values which was the cause of both issues, should hopefully be behaving now.

Anytime. 👍 

Thank you for making the rats and crocs fit for purpose again. LGTM.
