### PR TITLE
tr2/box: fix regression in Box_CalculateTarget

### LINKED ISSUE #1936: TR2X bug: shark can get above broken glass floor
**Regression since:** [0.1](https://github.com/LostArtefacts/TR2X/releases/tag/0.1)

________________

1. `/play 8`
2. `/tp 46 3 81`

20241122_145250_Wreck_of_the_Maria_Doria

**Edit:** If relevant, this particular room has no water.

Screenshot

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1936.

### CODE REVIEW

File: src/tr2/game/box.c [hunk 1]
```diff
@@ -248,18 +248,16 @@ TARGET_TYPE __cdecl Box_CalculateTarget(
...
-        int32_t height = box->height;
         if (lot->fly != 0) {
-            height -= WALL_L;
-        }
-        if (target->y > height - WALL_L) {
-            target->y = height - WALL_L;
+            CLAMPG(target->y, box->height - WALL_L);
+        } else {
+            CLAMPG(target->y, box->height);
         }
```
Comment (rr-) [inline src/tr2/game/box.c:255]: This is the most important part, the rest is cosmetics.

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍

**Review by walkawayy — APPROVED** [review]
