### PR TITLE
tr2/savegame: test object IDs rather than function pointers

### LINKED ISSUE #1930: TR2X bug: push block collision isn't being saved
**Dev snapshot:** 0.6-170-gcbae162 (latest)

_____________

**Steps to reproduce:**

1. `/play 1`
2. `/tp push`
3. move the block
4. `/save 1`
5. `/load 1`

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #1930.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

For some reason, the function pointer tests when loading a save were not passing in the debug build, so these have been changed to check the object IDs instead (pushblocks, puzzle slots and pickup items).

No changelog entry as it only affected debug.

### CODE REVIEW

File: src/tr2/game/objects/vars.h [hunk 1]
```diff
@@ -4,3 +4,5 @@
 
 extern const GAME_OBJECT_ID g_DoorObjects[];
 extern const GAME_OBJECT_ID g_TrapdoorObjects[];
+extern const GAME_OBJECT_ID g_MovableBlockObjects[];
+extern const GAME_OBJECT_ID g_PuzzleHoleObjects[];
```
Comment (rr-) [inline src/tr2/game/objects/vars.h]: Can we declare these in libtrx?

**Review by walkawayy — APPROVED** [review]

**Review by rr- — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
LGTM 👍
