### PR TITLE
lara/col/climb: fix ladder woes

### LINKED ISSUE #5169: [Bug] Lara cannot climb up on a triangle surface?
### Game type

Original game

### Game

TR3

### TRX version

1.4

### Operating system

Windows 10

### GPU

NVIDIA GeForse GTX 1050ti

### Describe the bug in plain terms, and write the shortest steps that reproduce it.

She cannot climb when the reaching point isn't anything but a flat square? This doesn't occur in the original game, only on the current TR3 dev build (1.4) for London.

### What did you expect instead?

To climb up normally

### Attachments

https://github.com/user-attachments/assets/627abdf1-9793-49bc-b4a1-25800baf1637

### Before submitting

- [x] I included enough detail to reproduce this.
- [x] I attached `TRX.log` and any saves, media, or custom level files needed to reproduce this.
- [x] This issue covers one bug.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #5169.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/develop/docs/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

TR3 uses a general X/Z shift of 4 for hanging and ladder checks, whereas TR1/2 both use 2. We had this version gate in place in one area but it was missing in two others, which seems to be the cause of the faulty ladder in Thames Wharf.

Also fixed Lara going from ladder to crouch in this area when pulling up, which only became evident with the above fix.

### CODE REVIEW

**Review by aredfan — APPROVED** [review]

File: src/trx/game/lara/col/climb.c [hunk 1]
```diff
@@ -808,7 +808,7 @@ static void M_UpLadder(ITEM *const item, COLL_INFO *const coll)
         item->goal_anim_state = LS(LS_CLIMB_STANCE);
         Lara_Animate(item);
         if (ABS(ledge_l - ledge_r) <= 120) {
-            if (result_r == CLIMB_RESULT_NEG && result_l == CLIMB_RESULT_NEG) {
+            if (result_r == CLIMB_RESULT_NEG || result_l == CLIMB_RESULT_NEG) {
```
Comment (rr-) [inline src/trx/game/lara/col/climb.c:811]: Are we sure about this?  What does tomb3 say?

**Review by rr- — APPROVED** [review]

File: src/trx/game/lara/col/climb.c (hunk 1 above)
Comment (lahm86) [reply src/trx/game/lara/col/climb.c:811]: Yes, should be good now. This isn't in TR3 originally, I took it from TR5. But I misread the condition originally. TR2/3 doesn't compare anything beyond `ABS(ledge_l - ledge_r) <= 120` as the earlier condition guards the climb result states.
