### PR TITLE
mutant: fix explosion damage

### LINKED ISSUE #1758: TR1: Exploding mummy kills Lara even when far away
Hello again, sorry to bother you with all these issues.

In the TR1 level "Obelisk of Khamoon" there are mummies that explode when killed, dealing damage to Lara unless she is sufficiently far away. In TR1X these mummies always insta-kill Lara even when she is far away.

As you can see in the video below, Lara is standing on one end of a bridge while a mummy stands on the other end, just within her line of fire. When Lara shoots the mummy and it explodes, she immediately dies despite standing far away with full health.

The save file from the video: [save_tr1_11.dat.gz](https://github.com/user-attachments/files/17531136/save_tr1_11.dat.gz)

https://github.com/user-attachments/assets/3256a8db-b6a2-43fc-9525-a03ffc8c80db

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #1758.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fixed mutant explosions sometimes heavily damaging Lara even if they missed.

### CODE REVIEW

**Comment by walkawayy** [comment]
Testing chart:

| Explosion injection | Enemy                         | Expected behavior
| --- | --- | ---
| Off                 | Mummy in Qualopec             | Stand and fall, no explosions, no damage
| On                  | Mummy in Qualopec             | Stand and fall, no explosions, no damage
| Off                 | Non-exploding Mutant in Egypt | Explode without explosion sprites, deal damage from body parts
| On                  | Non-exploding Mutant in Egypt | Explode without explosion sprites, deal damage from body parts
| Off                 | Exploding mutant in Atlantis  | Explode with explosion sprites, deal damage from body parts
| On                  | Exploding Mutant in Atlantis  | Explode with explosion sprites, deal damage from body parts
| Off                 | `/abortion`                   | Explode Lara without explosion sprites
| On                  | `/abortion`                   | Explode Lara with explosion sprites

**Comment by walkawayy** [comment]
@aredfan I think all my testing looked good. Remove the `"data/injections/explosion.bin",` in the gameflow to test the scenarios without the injection. I think it behaves like the PS1 version if not injected: https://youtu.be/dwFzJ3eVjRs?t=208

File: src/tr1/game/objects/effects/body_part.c [hunk 1]
```diff
@@ -58,7 +61,9 @@ void BodyPart_Control(int16_t fx_num)
             fx->speed = 0;
             fx->frame_num = 0;
             fx->counter = 0;
-            fx->object_id = O_EXPLOSION_1;
+            if (Mutant_EnableExplosion()) {
+                fx->object_id = O_EXPLOSION_1;
+            }
```
Comment (walkawayy) [inline src/tr1/game/objects/effects/body_part.c]: I'm not positive this check is necessary. 🤔

Comment (rr-) [reply src/tr1/game/objects/effects/body_part.c]: If we don't assing fx->object_id, the game should crash not knowing what object is tied to the created effect.

Comment (walkawayy) [reply src/tr1/game/objects/effects/body_part.c]: The game doesn't crash for me with this addition. And the behavior matches with the `Testing chart` above. Maybe @lahm86 has an idea.

I understand wanting to match the OG behavior, but it makes me confused about why we inject the explosion sprite if we don't want to use it in non-OG cases.

**Comment by aredfan** [comment]
Each of the listed behaviours for mutants are working as expected.

The explosion sprites don't seem to work when using `/abortion` in some of the levels (1, 3, 4).

File: src/tr1/game/objects/effects/body_part.c (hunk 1 above)
Comment (rr-) [reply src/tr1/game/objects/effects/body_part.c]: ~~To clarify, any FX that doesn't have its `object_id` set is considered not valid (see `Effect_Control`, `Effect_Draw` which use this property unconditionally). Not setting it also explains why the explosion sprites are not working with `/abortion`, which is the main reason why we inject the sprites to begin with.~~

Forget my earlier comments – the code converts the body part FX into an explosion, rather than creating a new `FX` for it. It's not ideal but it's OK.

Comment (lahm86) [reply src/tr1/game/objects/effects/body_part.c]: Ideally `BodyPart_Control` would know which object it's related to, or have a "do explode" flag passed to it from `Effect_ExplodingDeath` (which knows about the item). But that would mean storing it somewhere - maybe it could be packed into another field?

Comment (rr-) [reply src/tr1/game/objects/effects/body_part.c]: Upon examining the code closer, the explosions can already be turned on or off by making the damage passed from `Effect_ExplodingDeath` positive or negative, respectively. So for the overall fix, it's sufficient to replace `FLYER_SMARTNESS` with `FLYER_PART_DAMAGE` which was likely a typo.

File: src/tr1/game/lara/cheat.c [hunk 2]
```diff
@@ -114,7 +114,7 @@ void Lara_Cheat_Control(void)
                 g_Lara.uzis.ammo = 5000;
                 Sound_Effect(SFX_LARA_HOLSTER, NULL, SPM_ALWAYS);
             } else if (as == LS_SWAN_DIVE) {
-                Effect_ExplodingDeath(g_Lara.item_num, -1, 0);
+                Effect_ExplodingDeath(g_Lara.item_num, -1, 1);
```
Comment (walkawayy) [inline src/tr1/game/lara/cheat.c:117]: This causes explosions similar to `/abortion` if the original TR2+ exploding Lara cheat is performed.

I did not change the `/kill` command to have explosions / damage since that is a testing cheat to kill an enemy and avoid enemies. I don't think it makes sense to cause explosions that hurt Lara in that scenario.

**Comment by walkawayy** [comment]
This will require a retest. Sorry @aredfan.

File: src/tr1/game/lara/cheat.c (hunk 2 above)
Comment (rr-) [reply src/tr1/game/lara/cheat.c:117]: Sounds good. Let's make sure we document this in the changelog, though.

**Review by rr- — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
Retested all scenarios, LGTM. 👍
