### PR TITLE
tr2/inventory: fix level number for play any level

### LINKED ISSUE #2560: TR2X bug: play any level can hang the game
If play any level is enabled, but the GF has been modified to exclude the gym, selecting a level from the passport will hang the game.

[TR2X_gf.zip](https://github.com/user-attachments/files/19015118/TR2X_gf.zip)

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #2560.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This increments the selected level to play only if there is a gym level present.

### CODE REVIEW

File: src/libtrx/game/game_flow/common.c [hunk 1]
```diff
@@ -231,6 +231,11 @@ const GF_LEVEL *GF_GetLevelBefore(const GF_LEVEL *const level)
     return nullptr;
 }
 
+bool GF_IsGymAvailable(void)
+{
+    return GF_GetGymLevel() != nullptr;
+}
```
Comment (rr-) [inline src/libtrx/game/game_flow/common.c]: IMO it's a bit superfluous. I think not long ago we have removed this getter in favor of direct comparisons.

**Review by rr- — APPROVED** [review]

File: src/libtrx/game/game_flow/common.c (hunk 1 above)
Comment (lahm86) [reply src/libtrx/game/game_flow/common.c]: Thanks, simplified.

**Review by aredfan — APPROVED** [review]

**Review by rr- — APPROVED** [review]
