### PR TITLE
overlay: fix pausing pickups

### LINKED ISSUE #2319: TRX bug: varying behaviour of HUD pickups if the inventory/pause screens is opened
The OG behaviour of HUD sprites is it pauses when the inventory is open, and resumes displaying when the inventory is closed. With that in mind, I've created these tables to help outline the issue with sprite and 3d pickups in both TRX games.

_____________________

**Inventory**

| Game | Pickup type | Does the HUD pickup pause when the inventory is open? | Regression since |
|------|-------------|-------------------------------------------------------|------------------|
| TR1  | sprite      | no                                                    | [4.1](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.1)              |
| TR1  | 3d          | partially*                                            | [2.16](https://github.com/LostArtefacts/TRX/releases/tag/tr1-2.16)             |
| TR2  | sprite      | no                                                    | [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6)              |
| TR2  | 3d          | no                                                    | [0.6](https://github.com/LostArtefacts/TRX/releases/tag/tr2-0.6)              |

**Pause screen**

| Game | Pickup type | Does the HUD pickup pause when the game is paused? | Regression since |
|------|-------------|----------------------------------------------------|------------------|
| TR1  | sprite      | no                                                 | [4.1](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.1)              |
| TR1  | 3d          | partially*                                         | [4.1](https://github.com/LostArtefacts/TRX/releases/tag/tr1-4.1)              |
| TR2  | sprite      | yes ✓                                              | N/A              |
| TR2  | 3d          | yes ✓                                              | N/A              |

________________

*Opening the inventory/pause screens doesn't exactly pause the 3d pickup, it merely stops at the next part of the animation.  Try pausing when the pickup is still moving into the screen, when it's rotating, and when it's moving away from the screen to see what I mean.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #2319.

### CODE REVIEW

**Review by lahm86 — APPROVED** [review]

File: src/tr2/game/overlay.c [hunk 1]
```diff
@@ -343,8 +302,80 @@ void Overlay_DrawAmmoInfo(void)
     }
 }
 
-void Overlay_InitialisePickUpDisplay(void)
+void M_DrawModeInfo(void)
```
Comment (walkawayy) [inline src/tr2/game/overlay.c:305]: Would a better name be something like `M_DisplayTimerCount`?

**Review by aredfan — APPROVED** [review]
The issue is fixed across the board.  Thank you for your hard work. 👍

File: src/tr2/game/overlay.c (hunk 1 above)
Comment (rr-) [reply src/tr2/game/overlay.c:305]: This is about showing text such as `Bilinear filter: on/off` once you press several keys. I think the name is good, but we'll have to revamp this module either way when moving to libtrx. I have something on my mind, which should let us remove some members from the god object `g_GameInfo`, simplify the overlay API and the relationships between widgets, but I'm not yet ready to take that on ATM.
