### PR TITLE
tr2/data: fix faulty Ice Palace zoning data

### LINKED ISSUE #3000: OG bug: faulty box/overlap data in Ice Palace
Found by aredfan, notice how the Yetis can't reach Lara in this position. If you `/flip` the behaviour returns to normal.

[savegame.zip](https://github.com/user-attachments/files/20264718/savegame.zip)

The flipmap sector boxes are very messy here.

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #3000.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

This fixes zoning data in Ice Palace to resolve the yetis getting stuck near the area at the start.

Ref: https://github.com/LostArtefacts/TRXInjectionTool/pull/49

### CODE REVIEW

File: src/libtrx/game/pathing/box.c [hunk 1]
```diff
@@ -55,6 +56,27 @@ int16_t *Box_InitialiseOverlaps(const int32_t num_overlaps)
     return m_Overlaps;
 }
 
+bool Box_IsUsableZoneIndex(const int32_t zone_idx)
+{
+#if TR_VERSION == 2
+    // TODO: work out why these checks are in OG.
```
Comment (rr-) [inline src/libtrx/game/pathing/box.c:62]: Very good TODO. Thank you.

**Review by rr- — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
The issue is fixed, thank you. 👍
