### PR TITLE
grenade: fix kills counting as two kills

### LINKED ISSUE #1560: OG bug: killing enemies with grenades count as 2 kills
[https://www.tombraiderforums.com/showthread.php?p=8251220](https://www.tombraiderforums.com/showthread.php?p=8251220)

When this issue is being worked on - it'll be worth checking the black skidoo riders, bird monster and the dragon.

### PR DESCRIPTION
**Pull request by walkawayy**
Resolves #1560.

#### Checklist

- [X] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [X] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description
Fix grenades counting as double hits and kills in the game statistics.

### CODE REVIEW

**Comment by walkawayy** [comment]
@aredfan I guess double check if the hit count is bugged or not in this PR. Based on your comment in the issue, it seems only the kill count is bugged. I wonder if this PR broke the hit count? Like is it causing grenades to do 1 kill and 0 hits.

File: src/tr2/game/objects/general/grenade.c [hunk 1]
```diff
@@ -119,17 +119,7 @@ void __cdecl Grenade_Control(int16_t item_num)
         } else {
             // XXX: missing check if obj is intelligent?
             Gun_HitTarget(target_item, NULL, 30);
-
             explode = true;
-            g_SaveGame.statistics.hits++;
-
-            if (target_item->hit_points <= 0) {
-                g_SaveGame.statistics.kills++;
```
Comment (lahm86) [inline src/tr2/game/objects/general/grenade.c:127]: I think this is the only line that needs removed (127). Currently, grenade hits aren't recorded and the enemy doesn't actually explode, just dies normally.

Comment (walkawayy) [reply src/tr2/game/objects/general/grenade.c:127]: Oops yes. I misread the TR2Main code. I don't think it ever fixed the issue.

Comment (walkawayy) [reply src/tr2/game/objects/general/grenade.c:127]: I'm confused though. Because:
`Gun_FireWeapon` has:
`g_SaveGame.statistics.shots++;` and `g_SaveGame.statistics.hits++;`

and `Gun_Rifle_FireGrenade` has another:
`g_SaveGame.statistics.shots++;`

while `Grenade_Control` has:
`g_SaveGame.statistics.hits++;`


Oh `Gun_FireWeapon` is not called in `Gun_Rifle_FireGrenade` or in `Gun_Rifle_FireHarpoon` while it **is** called in `Gun_Rifle_FireM16` and `Gun_Rifle_FireShotgun`. It must be because shots/hits are determined by the grenade / harpoon control functions because they rely on missile collision while the normal weapons don't have to account for that.

**Review by rr- — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
LGTM, and thank you. 👍

**Review by lahm86 — APPROVED** [review]
