### PR TITLE
creature: fix dead water creature placement

### LINKED ISSUE #1031: OG bug: dead crocodiles float when rooms are drained
image

### PR DESCRIPTION
**Pull request by lahm86**
Resolves #1031.

#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

This moves the logic for shifting dead rats and crocodiles into shared functions in `creature.c` to resolve inconsistencies between the two and to cover all scenarios. Once a dead hybrid creature has been converted to its land type, it will remain in that state permanently.

I've also introduced an idiom in `Item_SwitchToObjAnim` that if you pass a negative frame number, this will be inferred as meaning the frame should be relative from the end of the animation.

### CODE REVIEW

File: src/game/objects/creatures/rat.c [hunk 1]
```diff
@@ -49,6 +49,13 @@ typedef enum {
 
 static BITE_INFO m_RatBite = { 0, -11, 108, 3 };
 
+static const HYBRID_INFO m_RatInfo = { .land.id = O_RAT,
+                                       .land.active_anim = RAT_EMPTY,
+                                       .land.death_anim = RAT_DIE_ANIM,
+                                       .land.death_state = RAT_DEATH,
+                                       .water.id = O_VOLE,
+                                       .water.active_anim = VOLE_EMPTY };
```
Comment (rr-) [inline src/game/objects/creatures/rat.c]: Will it be formatted any better if we put a trailing comma inside the struct?

File: src/game/creature.c [hunk 2]
```diff
@@ -706,3 +711,80 @@ bool Creature_ShootAtLara(
...
+bool Creature_TestHybridState(
+    int16_t item_num, int32_t *wh, const HYBRID_INFO *info)
+{
+    // Test the environment for a hybrid creature. Record the water height and
+    // return whether or not a type conversion has taken place.
+    ITEM_INFO *item = &g_Items[item_num];
+    return item->object_number == info->land.id
+        ? Creature_TestLandState(item_num, wh, info)
+        : Creature_TestWaterState(item_num, wh, info);
+}
```
Comment (rr-) [inline src/game/creature.c:727]: The name `Test` suggests that the function doesn't mutate the global state, while it changes up item animations and object numbers. Furthermore `Hybrid` is unclear until the reader already knows the concept behind it. How about `Creature_EnsureHabitat` or similar?

File: src/game/objects/creatures/rat.c (hunk 1 above)
Comment (lahm86) [reply src/game/objects/creatures/rat.c]: It did, thanks. I've done the same in `crocodile.c` for consistency.

File: src/game/creature.c (hunk 2 above)
Comment (lahm86) [reply src/game/creature.c:727]: Good point, thanks. Now renamed as above, and the statics have been renamed similarly too. I've also refactored slightly to call `Room_GetWaterHeight` in the wrapper function rather than in each state function for a little less repetition.

**Review by rr- — APPROVED** [review]

File: src/game/objects/creatures/rat.c [hunk 3]
```diff
@@ -49,6 +49,15 @@ typedef enum {
...
 static BITE_INFO m_RatBite = { 0, -11, 108, 3 };
 
+static const HYBRID_INFO m_RatInfo = {
+    .land.id = O_RAT,
+    .land.active_anim = RAT_EMPTY,
+    .land.death_anim = RAT_DIE_ANIM,
+    .land.death_state = RAT_DEATH,
+    .water.id = O_VOLE,
+    .water.active_anim = VOLE_EMPTY,
+};
```
Comment (walkawayy) [inline src/game/objects/creatures/rat.c:59]: Why does the water state not need a death anim/state?

**Review by walkawayy — APPROVED** [review]
All testing LGTM.

File: src/game/objects/creatures/rat.c (hunk 3 above)
Comment (lahm86) [reply src/game/objects/creatures/rat.c:59]: We never switch to the water death state in the environment checks, so it's not needed. These are the only possible scenarios:
- Killed in water (normal control uses water death anim)
  - Room drained - switch to land death
  - Room re-flooded - remain in land death
- Killed on land
  - Room flooded - remain in land death
  - Room re-drained - remain in land death

The only difference is for crocodiles - if they're killed in water and that room is then drained, but there is still another water room below, they'll remain in the water anim death state.
