### PR TITLE
tr2/game-flow: fix carrying stats across cutscenes

### LINKED ISSUE #2478: TR2X bug: end-level stats are empty if preceded by a cutscene
For example, play Great Wall, pick up an item, kill an enemy, and allow the timer to tick for a while. If you then level skip, skip the cutscene, the end level stats are empty. Inventory stats are fine.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TRX/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change
- [x] I have added a readme entry about my new feature or OG bug fix, or it is a different change

#### Description

Resolves #2478.

### CODE REVIEW

File: src/tr2/decomp/savegame.c [hunk 1]
```diff
@@ -19,6 +19,7 @@
 #include "game/requester.h"
 #include "game/room.h"
 #include "game/shell.h"
+#include "game/stats.h"
```
Comment (lahm86) [inline src/tr2/decomp/savegame.c]: I think this include is needed in `sequencer_events.c` - currently get a compilation warning, and the final game stats are empty.

Comment (rr-) [reply src/tr2/decomp/savegame.c]: Right – thanks for spotting this, I added it to the wrong file.

Comment (rr-) [reply src/tr2/decomp/savegame.c]: @lahm86 Fixed.

**Review by lahm86 — APPROVED** [review]

**Review by aredfan — APPROVED** [review]
