### PR TITLE
Fix crystals mode issues on develop

### LINKED ISSUE #1126: Save crystals woes on develop
With `"enable_save_crystals" : true`:
* the Load Game page in the in-game passport doesn't open the menu to choose a save, instead it just loads your last save, or if you've restarted the level, it restarts the level again
* Exit to Title closes the game instead of returning to the title menu (also happens with `"enable_save_crystals" : false`)
* the ingame passport defaults to the Load Game page when opened instead of the Restart Level page (minor inconsistency with PS1 TR)

Happens on develop only, caused by the passport refactor.

### PR DESCRIPTION
**Pull request by rr-**
#### Checklist

- [x] I have read the [coding conventions](https://github.com/LostArtefacts/TR1X/blob/master/CONTRIBUTING.md#coding-conventions)
- [x] I have added a changelog entry about what my pull request accomplishes, or it is an internal change

#### Description

Resolves #1126

### CODE REVIEW

File: src/game/option/option_passport.c [hunk 1]
```diff
@@ -345,19 +343,17 @@ static void Option_PassportInitNewGameRequester(void)
...
-            g_GameInfo.current_save_slot = select - 1;
-            g_GameInfo.passport_selection = pending_mode;
-        } else {
-            if (g_InvMode != INV_SAVE_MODE && g_InvMode != INV_SAVE_CRYSTAL_MODE
-                && g_InvMode != INV_LOAD_MODE) {
-                g_Input = (INPUT_STATE) { 0 };
-                g_InputDB = (INPUT_STATE) { 0 };
-            }
-        }
+    if (select == 0) {
```
Comment (walkawayy) [inline src/game/option/option_passport.c:346]: Love this change.

**Review by walkawayy — APPROVED** [review]

**Review by lahm86 — APPROVED** [review]
